name: Setup
description: Setup dependencies for CI

runs:
  using: composite
  steps:
    - name: Detect terraform version
      run: printf "TF_VERSION=%s" $(cat ./.terraform-version) >> $GITHUB_ENV
      shell: bash

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v3 # https://github.com/hashicorp/setup-terraform
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Detect terragrunt version
      run: printf "TG_VERSION=%s" $(cat ./.terragrunt-version) >> $GITHUB_ENV
      shell: bash

    - name: Install terragrunt
      run: ./scripts/github_action/install_terragrunt.sh
      shell: bash

    - name: Install tfcmt
      run: ./scripts/github_action/install_tfcmt.sh
      shell: bash
      env:
        TFCMT_VERSION: 3.0.1

    - uses: terraform-linters/setup-tflint@v3
      name: Setup TFLint
      with:
        tflint_version: v0.34.1 # 常にterraformとのバージョンの互換性があるか確認する必要があるので注意 https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/compatibility.md


