name: Additional commit depending on updating terraform provider

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  add-darwin-amd64:
    name: Add darwin_amd64 platform
    if: startsWith(github.head_ref, 'renovate-terraform-provider/')
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions: # https://docs.github.com/ja/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
      id-token: write # IDトークンの取得に必要な情報を環境変数に設定してもらえる。具体的にはConfigure AWS credentialsのwith内のとこ。
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect terraform version
        run: printf "TF_VERSION=%s" $(cat .terraform-version) >> $GITHUB_ENV

      - name: Detect terragrunt version
        run: printf "TG_VERSION=%s" $(cat .terragrunt-version) >> $GITHUB_ENV

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Install tfcmt
        run: ./scripts/github_action/install_tfcmt.sh

      - name: Install terragrunt
        run: ./scripts/github_action/install_terragrunt.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.ARN_TO_ASSUME_ROLE }}
          role-session-name: GitHubActions
          aws-region: us-west-1

      - name: Run terragrunt init -upgrade
        run: terragrunt run-all init -upgrade

      - name: Add darwin_amd64 platform
        run: terragrunt run-all providers lock -platform=darwin_amd64 -platform=linux_amd64 --terragrunt-non-interactive

      - name: Run terragrunt validate
        run: ./scripts/github_action/terragrunt_validate.sh

      - name: Run terragrunt plan
        run: |
          CHANGED_DIRS=$(git --no-pager diff origin/main..HEAD --name-only ./staging ./production | xargs -I{} dirname {} | awk '!a[$0]++{print}')
          $GITHUB_WORKSPACE/scripts/github_action/terragrunt_plan.sh $CHANGED_DIRS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./environments

      - name: Commit terraform.lock.hcl files
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          message: 'Add platform darwin_amd64 to all terraform.lock.hcl'
          default_author: github_actions
