name: Add darwin_amd64 platform to terraform.lock.hcl

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:  
  add-darwin-amd64:
    name: Add darwin_amd64
    if: startsWith(github.head_ref, 'renovate-terraform-provider/')
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions: # https://docs.github.com/ja/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
      id-token: write # IDトークンの取得に必要な情報を環境変数に設定してもらえる。具体的にはConfigure AWS credentialsのwith内のとこ。
      contents: write
      pull-requests: write

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Number of commits to fetch. 0 indicates all history for all branches and tags. Default: 1

      - name: Detect terraform version
        run: printf "TF_VERSION=%s" $(cat .terraform-version) >> $GITHUB_ENV
      
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1 # https://github.com/hashicorp/setup-terraform
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Install tfcmt
        run: ./scripts/github_action/install_tfcmt.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1 # https://github.com/aws-actions/configure-aws-credentials
        with:
          role-to-assume: ${{ secrets.ARN_TO_ASSUME_ROLE }}
          role-session-name: GitHubActions
          aws-region: us-west-2 # オレゴン

      - name: Add darwin_amd64 platform and execute terraform plan
        run: ./scripts/github_action/add_darwin_amd64.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
          PULL_REQUEST_NUMBER: ${{ github.event.number }} # pull_request イベントであることに依存なので注意。https://docs.github.com/ja/developers/webhooks-and-events/events/github-event-types#pullrequestevent
          REPOSITORY_OWNER: jinugasachio
          REPOSITORY_NAME: advanced-ecs-on-fargate
    
      - name: Commit lock files
        uses: EndBug/add-and-commit@v7
        with:
          add: '.'
          message: 'Add platform darwin_amd64 to all terraform.lock.hcl'
          default_author: github_actions
