name: Terragrunt apply

on:
  push:
    branches:
      - main

jobs:
  run-terragrunt-apply:
    name: Run terragrunt apply
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions: # https://docs.github.com/ja/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
      id-token: write # IDトークンの取得に必要な情報を環境変数に設定してもらえる。具体的にはConfigure AWS credentialsのwith内のとこ。
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Number of commits to fetch. 0 indicates all history for all branches and tags. Default: 1

      - name: Detect terraform version
        run: printf "TF_VERSION=%s" $(cat .terraform-version) >> $GITHUB_ENV

      - name: Detect terragrunt version
        run: printf "TG_VERSION=%s" $(cat .terragrunt-version) >> $GITHUB_ENV

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1 # https://github.com/hashicorp/setup-terraform
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Run terraform fmt
        run: ./scripts/github_action/terraform_fmt.sh

      - name: Install tfcmt
        run: ./scripts/github_action/install_tfcmt.sh

      - name: Install terragrunt
        run: ./scripts/github_action/install_terragrunt.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1 # https://github.com/aws-actions/configure-aws-credentials
        with:
          role-to-assume: ${{ secrets.ARN_TO_ASSUME_ROLE }}
          role-session-name: GitHubActions
          aws-region: us-west-1

      - name: Run terragrunt validate
        run: ./scripts/github_action/terragrunt_validate.sh

      - name: Run terragrunt apply
        run: |
          CHANGED_DIRS=$(git --no-pager diff HEAD..HEAD^ --name-only ./environments/production | xargs -I{} dirname {} | awk '!a[$0]++{print}')
          ./scripts/github_action/terragrunt_apply.sh $CHANGED_DIRS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
