name: Terraform plan

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:  
  execute-terraform-plan:
    name: Execute terraform plan
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        shell: bash
        working-directory: ./environments/production
    permissions: # https://docs.github.com/ja/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
      id-token: write # IDトークンの取得に必要な情報を環境変数に設定してもらえる。具体的にはConfigure AWS credentialsのwith内のとこ。
      contents: write
      pull-requests: write

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Number of commits to fetch. 0 indicates all history for all branches and tags. Default: 1

      - name: Detect terraform version
        run: printf "TF_VERSION=%s" $(cat $GITHUB_WORKSPACE/.terraform-version) >> $GITHUB_ENV

      - name: Detect terragrunt version
        run: printf "TG_VERSION=%s" $(cat $GITHUB_WORKSPACE/.terragrunt-version) >> $GITHUB_ENV
      
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1 # https://github.com/hashicorp/setup-terraform
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Execute terraform fmt
        run: terraform fmt -diff -check -recursive .
      
      - name: Install tfcmt
        run: ${GITHUB_WORKSPACE}/scripts/github_action/install_tfcmt.sh

      - name: Install terragrunt
        run: $GITHUB_WORKSPACE/scripts/github_action/install_terragrunt.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1 # https://github.com/aws-actions/configure-aws-credentials
        with:
          role-to-assume: ${{ secrets.ARN_TO_ASSUME_ROLE }}
          role-session-name: GitHubActions
          aws-region: us-west-1

      - name: Run terraform validate
        run: terragrunt run-all validate --terragrunt-non-interactive
      
      - uses: terraform-linters/setup-tflint@v1
        name: Setup TFLint
        with:
          tflint_version: v0.34.1 # 常にterraformとのバージョンの互換性があるか確認する必要があるので注意 https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/compatibility.md

      - name: Run tflint init
        run: tflint --init --config $GITHUB_WORKSPACE/.tflint.hcl

      - name: Execute tflint
        run: |
          terraform_dirs=$($GITHUB_WORKSPACE/scripts/github_action/detect_terraform_dirs.sh)
          $GITHUB_WORKSPACE/scripts/github_action/tflint.sh $terraform_dirs

      - name: Run terraform plan
        run: terragrunt run-all plan --terragrunt-tfpath $GITHUB_WORKSPACE/scripts/github_action/terraform_plan.sh
