name: Terraform apply

on:
  push:
    branches:
      - main

jobs:  
  execute-terraform-apply:
    name: terraform apply
    runs-on: ubuntu-latest
    permissions: # https://docs.github.com/ja/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
      id-token: write # IDトークンの取得に必要な情報を環境変数に設定してもらえる。具体的にはConfigure AWS credentialsのwith内のとこ。
      contents: write
      pull-requests: write

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Number of commits to fetch. 0 indicates all history for all branches and tags. Default: 1

      - name: Detect terraform version
        run: printf "TF_VERSION=%s" $(cat .terraform-version) >> $GITHUB_ENV
      
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1 # https://github.com/hashicorp/setup-terraform
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Install tfcmt
        run: ./scripts/github_action/install_tfcmt.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1 # https://github.com/aws-actions/configure-aws-credentials
        with:
          role-to-assume: ${{ secrets.ARN_TO_ASSUME_ROLE }}
          role-session-name: GitHubActions
          aws-region: us-west-2 # オレゴン


      - name: Detect PR number pushed to main
        uses: jwalton/gh-find-current-pr@v1
        id: detect-pr
        with:
          state: open

      - run: echo "Your PR is ${PR}"
        env:
          PR: ${{ steps.detect-pr.outputs.pr }}

      - name: Terraform apply with tfcmt
        run: ./scripts/github_action/terraform_apply.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
          PULL_REQUEST_NUMBER: ${{ steps.detect-pr.outputs.pr }}
          REPOSITORY_OWNER: jinugasachio
          REPOSITORY_NAME: advanced-ecs-on-fargate
