name: Static analysis for security

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-tfsec:
    name: Run tfsec
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tfsec
        uses: reviewdog/action-tfsec@9035391f03cece1102e9b59e2aa1f143a64b558d
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: .
          level: warning # Get more output from reviewdog
          reporter: github-pr-review # Change reviewdog reporter
          filter_mode: nofilter # Check all files, not just the diff
          fail_on_error: false # Fail action if errors are found
          flags: -tee # Add debug flag to reviewdog
          tfsec_flags: --force-all-dirs
