name: TFlint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-terragrunt-plan:
    name: Run tflint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1 # https://github.com/aws-actions/configure-aws-credentials
        with:
          role-to-assume: ${{ secrets.ARN_TO_ASSUME_ROLE }}
          role-session-name: GitHubActions
          aws-region: us-west-1

      - uses: terraform-linters/setup-tflint@v1
        name: Setup TFLint
        with:
          tflint_version: v0.34.1 # 常にterraformとのバージョンの互換性があるか確認する必要があるので注意 https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/compatibility.md
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tflint init
        run: tflint --init --config ./.tflint.hcl

      - name: Run tflint
        run: |
          TF_DIRS=$(./scripts/github_action/detect_terraform_dirs.sh)
          ./scripts/github_action/tflint.sh $TF_DIRS
